import type { ModelsDevCatalog } from './modelsDev.ts';

/**
 * Bundled models.dev snapshot (shipped in the package). This guarantees the
 * catalog is rich and complete **offline and on first run** — before any network
 * fetch — so `getProvider`/`listProviders` stay synchronous and never depend on
 * connectivity. The live models.dev fetch (see `modelsDev.ts`) only *augments*
 * this: newer models, more providers, updated prices.
 *
 * Shape matches the models.dev api.json subset (`ModelsDevCatalog`) so one
 * normalizer handles both snapshot and live data. Regenerate periodically from
 * `https://models.dev/api.json` (curated to the providers Parallax ships).
 */
export const MODELS_DEV_SNAPSHOT: ModelsDevCatalog = {
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    env: ['ANTHROPIC_API_KEY'],
    models: {
      'claude-opus-4-8': {
        id: 'claude-opus-4-8',
        name: 'Claude Opus 4.8',
        cost: { input: 5, output: 25, cache_read: 0.5, cache_write: 6.25 },
        limit: { context: 1000000, output: 128000 },
        tool_call: true,
        reasoning: true,
        attachment: true,
        release_date: '2026-05-28',
      },
      'claude-opus-4-7': {
        id: 'claude-opus-4-7',
        name: 'Claude Opus 4.7',
        cost: { input: 5, output: 25, cache_read: 0.5, cache_write: 6.25 },
        limit: { context: 1000000, output: 128000 },
        tool_call: true,
        reasoning: true,
        attachment: true,
        release_date: '2026-04-14',
      },
      'claude-sonnet-4-6': {
        id: 'claude-sonnet-4-6',
        name: 'Claude Sonnet 4.6',
        cost: { input: 3, output: 15, cache_read: 0.3, cache_write: 3.75 },
        limit: { context: 1000000, output: 128000 },
        tool_call: true,
        reasoning: true,
        attachment: true,
        release_date: '2026-02-17',
      },
      'claude-haiku-4-5': {
        id: 'claude-haiku-4-5',
        name: 'Claude Haiku 4.5',
        cost: { input: 1, output: 5, cache_read: 0.1, cache_write: 1.25 },
        limit: { context: 200000, output: 64000 },
        tool_call: true,
        reasoning: true,
        attachment: true,
        release_date: '2025-10-15',
      },
    },
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    env: ['OPENAI_API_KEY'],
    models: {
      'gpt-4o': {
        id: 'gpt-4o',
        name: 'GPT-4o',
        cost: { input: 2.5, output: 10, cache_read: 1.25 },
        limit: { context: 128000, output: 16384 },
        tool_call: true,
        reasoning: false,
        attachment: true,
        release_date: '2024-05-13',
      },
      'gpt-4o-mini': {
        id: 'gpt-4o-mini',
        name: 'GPT-4o mini',
        cost: { input: 0.15, output: 0.6, cache_read: 0.075 },
        limit: { context: 128000, output: 16384 },
        tool_call: true,
        reasoning: false,
        attachment: true,
        release_date: '2024-07-18',
      },
      'gpt-4.1': {
        id: 'gpt-4.1',
        name: 'GPT-4.1',
        cost: { input: 2, output: 8, cache_read: 0.5 },
        limit: { context: 1047576, output: 32768 },
        tool_call: true,
        reasoning: false,
        attachment: true,
        release_date: '2025-04-14',
      },
      'o4-mini': {
        id: 'o4-mini',
        name: 'o4-mini',
        cost: { input: 1.1, output: 4.4, cache_read: 0.275 },
        limit: { context: 200000, output: 100000 },
        tool_call: true,
        reasoning: true,
        attachment: true,
        release_date: '2025-04-16',
      },
    },
  },
  nvidia: {
    id: 'nvidia',
    name: 'Nvidia',
    env: ['NVIDIA_API_KEY'],
    api: 'https://integrate.api.nvidia.com/v1',
    models: {
      'meta/llama-3.3-70b-instruct': {
        id: 'meta/llama-3.3-70b-instruct',
        name: 'Llama 3.3 70b Instruct',
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 4096 },
        tool_call: true,
        reasoning: false,
        attachment: false,
        release_date: '2024-11-26',
      },
      'nvidia/llama-3.1-nemotron-70b-instruct': {
        id: 'nvidia/llama-3.1-nemotron-70b-instruct',
        name: 'Llama 3.1 Nemotron 70B Instruct',
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 8192 },
        tool_call: true,
        reasoning: false,
        attachment: false,
        release_date: '2025-04-15',
      },
      'qwen/qwen2.5-coder-32b-instruct': {
        id: 'qwen/qwen2.5-coder-32b-instruct',
        name: 'Qwen2.5 Coder 32b Instruct',
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 4096 },
        tool_call: true,
        reasoning: false,
        attachment: false,
        release_date: '2024-11-06',
      },
    },
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    env: ['OPENROUTER_API_KEY'],
    api: 'https://openrouter.ai/api/v1',
    models: {
      'anthropic/claude-sonnet-4.5': {
        id: 'anthropic/claude-sonnet-4.5',
        name: 'Claude Sonnet 4.5',
        cost: { input: 3, output: 15, cache_read: 0.3, cache_write: 3.75 },
        limit: { context: 1000000, output: 64000 },
        tool_call: true,
        reasoning: true,
        attachment: true,
        release_date: '2025-09-29',
      },
      'openai/gpt-4o': {
        id: 'openai/gpt-4o',
        name: 'GPT-4o',
        cost: { input: 2.5, output: 10, cache_read: 1.25 },
        limit: { context: 128000, output: 16384 },
        tool_call: true,
        reasoning: false,
        attachment: true,
        release_date: '2024-05-13',
      },
      'moonshotai/kimi-k2': {
        id: 'moonshotai/kimi-k2',
        name: 'Kimi K2 0711',
        cost: { input: 0.57, output: 2.3 },
        limit: { context: 131072, output: 100352 },
        tool_call: true,
        reasoning: false,
        attachment: false,
        release_date: '2025-07-11',
      },
      'deepseek/deepseek-chat': {
        id: 'deepseek/deepseek-chat',
        name: 'DeepSeek Chat',
        cost: { input: 0.2574, output: 1.0287 },
        limit: { context: 163840, output: 16000 },
        tool_call: true,
        reasoning: false,
        attachment: false,
        release_date: '2025-12-01',
      },
    },
  },
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot AI',
    env: ['MOONSHOT_API_KEY'],
    api: 'https://api.moonshot.ai/v1',
    models: {
      'kimi-k2-0711-preview': {
        id: 'kimi-k2-0711-preview',
        name: 'Kimi K2 0711',
        cost: { input: 0.6, output: 2.5, cache_read: 0.15 },
        limit: { context: 131072, output: 16384 },
        tool_call: true,
        reasoning: false,
        attachment: false,
        release_date: '2025-07-14',
      },
      'moonshot-v1-128k': { id: 'moonshot-v1-128k', name: 'moonshot-v1-128k' },
      'moonshot-v1-32k': { id: 'moonshot-v1-32k', name: 'moonshot-v1-32k' },
    },
  },
};
